//! [TDBIN-BENCH-CORPUS] typeDiagram ADT + TDBIN columnar codec (layout major
//! 2), GENERATED by `packages/typediagram/src/converters/rust-tdbin.ts`
//! (`generateRustModule(model, { layout: 2 })`) from
//! `docs/benchmarks/tdbin-corpus.td`. The benchmark support fixtures and the
//! `golden_columnar.rs` vectors consume these types. The
//! `rust-tdbin-corpus.test.ts` vitest suite pins the emitted text and fails if
//! this file drifts from codegen; regenerate with
//! `node scripts/tdbin-regen-fixtures.mjs` rather than hand-editing.

// <<<GENERATED — rust-tdbin.ts generateRustModule (layout 2); do not edit by hand>>>
/// The `BenchDocument` record.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct BenchDocument {
    /// The `id` field.
    pub id: String,
    /// The `title` field.
    pub title: String,
    /// The `revision` field.
    pub revision: i64,
    /// The `nodes` field.
    pub nodes: Vec<BenchNode>,
    /// The `edges` field.
    pub edges: Vec<BenchEdge>,
    /// The `styles` field.
    pub styles: Vec<BenchStyle>,
    /// The `metadata` field.
    pub metadata: Vec<BenchMeta>,
}

/// The `BenchNode` record.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct BenchNode {
    /// The `id` field.
    pub id: String,
    /// The `label` field.
    pub label: String,
    /// The `x` field.
    pub x: f64,
    /// The `y` field.
    pub y: f64,
    /// The `width` field.
    pub width: f64,
    /// The `height` field.
    pub height: f64,
    /// The `selected` field.
    pub selected: bool,
    /// The `locked` field.
    pub locked: bool,
    /// The `tags` field.
    pub tags: Vec<String>,
}

/// The `BenchEdge` record.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct BenchEdge {
    /// The `id` field.
    pub id: String,
    /// The `from` field.
    pub from: String,
    /// The `to` field.
    pub to: String,
    /// The `label` field.
    pub label: Option<String>,
    /// The `weight` field.
    pub weight: f64,
    /// The `directed` field.
    pub directed: bool,
}

/// The `BenchStyle` record.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct BenchStyle {
    /// The `selector` field.
    pub selector: String,
    /// The `fill` field.
    pub fill: String,
    /// The `stroke` field.
    pub stroke: String,
    /// The `stroke_width` field.
    pub stroke_width: f64,
    /// The `rounded` field.
    pub rounded: bool,
}

/// The `BenchMeta` record.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct BenchMeta {
    /// The `key` field.
    pub key: String,
    /// The `value` field.
    pub value: String,
}

/// The `BenchEvent` union.
#[derive(Debug, Clone, PartialEq)]
pub enum BenchEvent {
    /// The `NodeCreated` variant.
    NodeCreated(BenchNodeCreated),
    /// The `NodeMoved` variant.
    NodeMoved(BenchNodeMoved),
    /// The `EdgeAdded` variant.
    EdgeAdded(BenchEdgeAdded),
    /// The `SelectionChanged` variant.
    SelectionChanged(BenchSelectionChanged),
    /// The `ViewChanged` variant.
    ViewChanged(BenchViewChanged),
    /// The `Heartbeat` variant.
    Heartbeat,
}

/// The `BenchEventBatch` record.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct BenchEventBatch {
    /// The `events` field.
    pub events: Vec<BenchEvent>,
}

/// The `BenchNodeCreated` record.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct BenchNodeCreated {
    /// The `document_id` field.
    pub document_id: String,
    /// The `node` field.
    pub node: BenchNode,
}

/// The `BenchNodeMoved` record.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct BenchNodeMoved {
    /// The `document_id` field.
    pub document_id: String,
    /// The `node_id` field.
    pub node_id: String,
    /// The `x` field.
    pub x: f64,
    /// The `y` field.
    pub y: f64,
}

/// The `BenchEdgeAdded` record.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct BenchEdgeAdded {
    /// The `document_id` field.
    pub document_id: String,
    /// The `edge` field.
    pub edge: BenchEdge,
}

/// The `BenchSelectionChanged` record.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct BenchSelectionChanged {
    /// The `document_id` field.
    pub document_id: String,
    /// The `node_ids` field.
    pub node_ids: Vec<String>,
    /// The `edge_ids` field.
    pub edge_ids: Vec<String>,
}

/// The `BenchViewChanged` record.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct BenchViewChanged {
    /// The `document_id` field.
    pub document_id: String,
    /// The `zoom` field.
    pub zoom: f64,
    /// The `offset_x` field.
    pub offset_x: f64,
    /// The `offset_y` field.
    pub offset_y: f64,
}

/// The `BenchMetricBatch` record.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct BenchMetricBatch {
    /// The `batch_id` field.
    pub batch_id: String,
    /// The `started_at_epoch_ms` field.
    pub started_at_epoch_ms: i64,
    /// The `sample_ids` field.
    pub sample_ids: Vec<i64>,
    /// The `valid` field.
    pub valid: Vec<bool>,
    /// The `latency_ms` field.
    pub latency_ms: Vec<f64>,
    /// The `payloads` field.
    pub payloads: Vec<Vec<u8>>,
    /// The `columns` field.
    pub columns: Vec<BenchMetricColumn>,
}

/// The `BenchMetricColumn` record.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct BenchMetricColumn {
    /// The `name` field.
    pub name: String,
    /// The `values` field.
    pub values: Vec<f64>,
}

impl tdbin::Struct for BenchDocument {
    const DATA_WORDS: u16 = 1;
    const PTR_WORDS: u16 = 6;
    const LAYOUT_HASH: u64 = 0xc531_c81b_85f9_5c4d;

    fn write_struct(&self, w: &mut tdbin::Writer, at: usize) -> Result<(), tdbin::EncodeError> {
        w.string(at, Self::DATA_WORDS, 0, Some(&self.id))?;
        w.string(at, Self::DATA_WORDS, 1, Some(&self.title))?;
        w.scalar(at, 0, tdbin::scalar::i64_bits(self.revision))?;
        w.column_list(at, Self::DATA_WORDS, 2, Some(&self.nodes))?;
        w.column_list(at, Self::DATA_WORDS, 3, Some(&self.edges))?;
        w.column_list(at, Self::DATA_WORDS, 4, Some(&self.styles))?;
        w.column_list(at, Self::DATA_WORDS, 5, Some(&self.metadata))?;
        Ok(())
    }

    fn read_struct(r: &tdbin::Reader<'_>, at: usize) -> Result<Self, tdbin::DecodeError> {
        let id = r.string(at, Self::DATA_WORDS, 0)?.unwrap_or_default();
        let title = r.string(at, Self::DATA_WORDS, 1)?.unwrap_or_default();
        let revision = tdbin::scalar::i64_from(r.scalar(at, 0)?);
        let nodes = r
            .column_list::<BenchNode>(at, Self::DATA_WORDS, 2)?
            .unwrap_or_default();
        let edges = r
            .column_list::<BenchEdge>(at, Self::DATA_WORDS, 3)?
            .unwrap_or_default();
        let styles = r
            .column_list::<BenchStyle>(at, Self::DATA_WORDS, 4)?
            .unwrap_or_default();
        let metadata = r
            .column_list::<BenchMeta>(at, Self::DATA_WORDS, 5)?
            .unwrap_or_default();
        Ok(Self {
            id,
            title,
            revision,
            nodes,
            edges,
            styles,
            metadata,
        })
    }
}

impl tdbin::Struct for BenchNode {
    const DATA_WORDS: u16 = 5;
    const PTR_WORDS: u16 = 4;
    const LAYOUT_HASH: u64 = 0xfcc1_13fe_4baf_ecdb;

    fn write_struct(&self, w: &mut tdbin::Writer, at: usize) -> Result<(), tdbin::EncodeError> {
        w.string(at, Self::DATA_WORDS, 0, Some(&self.id))?;
        w.string(at, Self::DATA_WORDS, 1, Some(&self.label))?;
        w.scalar(at, 0, tdbin::scalar::f64_bits(self.x))?;
        w.scalar(at, 1, tdbin::scalar::f64_bits(self.y))?;
        w.scalar(at, 2, tdbin::scalar::f64_bits(self.width))?;
        w.scalar(at, 3, tdbin::scalar::f64_bits(self.height))?;
        w.bool_bit(at, 4, 0, self.selected)?;
        w.bool_bit(at, 4, 1, self.locked)?;
        w.string_var_list(at, Self::DATA_WORDS, 2, 3, Some(&self.tags))?;
        Ok(())
    }

    fn read_struct(r: &tdbin::Reader<'_>, at: usize) -> Result<Self, tdbin::DecodeError> {
        let id = r.string(at, Self::DATA_WORDS, 0)?.unwrap_or_default();
        let label = r.string(at, Self::DATA_WORDS, 1)?.unwrap_or_default();
        let x = tdbin::scalar::f64_from(r.scalar(at, 0)?);
        let y = tdbin::scalar::f64_from(r.scalar(at, 1)?);
        let width = tdbin::scalar::f64_from(r.scalar(at, 2)?);
        let height = tdbin::scalar::f64_from(r.scalar(at, 3)?);
        let selected = r.bool_bit(at, 4, 0)?;
        let locked = r.bool_bit(at, 4, 1)?;
        let tags = match r.var_list(at, Self::DATA_WORDS, 2, 3)? {
            Some(column) => column.into_strings()?,
            None => Vec::new(),
        };
        Ok(Self {
            id,
            label,
            x,
            y,
            width,
            height,
            selected,
            locked,
            tags,
        })
    }
}

impl tdbin::ColumnGroup for BenchNode {
    const COLUMNS: u16 = 13;

    fn write_group<'v, I>(
        items: I,
        count: usize,
        w: &mut tdbin::Writer,
        at: usize,
    ) -> Result<(), tdbin::EncodeError>
    where
        I: Iterator<Item = &'v Self> + Clone,
        Self: 'v,
    {
        w.var_column(
            at,
            1,
            0,
            1,
            count,
            items.clone().map(|row| row.id.as_bytes()),
        )?;
        w.var_column(
            at,
            1,
            2,
            3,
            count,
            items.clone().map(|row| row.label.as_bytes()),
        )?;
        w.f64_column(at, 1, 4, count, items.clone().map(|row| row.x))?;
        w.f64_column(at, 1, 5, count, items.clone().map(|row| row.y))?;
        w.f64_column(at, 1, 6, count, items.clone().map(|row| row.width))?;
        w.f64_column(at, 1, 7, count, items.clone().map(|row| row.height))?;
        w.bit_column(at, 1, 8, count, items.clone().map(|row| row.selected))?;
        w.bit_column(at, 1, 9, count, items.clone().map(|row| row.locked))?;
        let tags_counts = items
            .clone()
            .map(|row| u32::try_from(row.tags.len()))
            .collect::<Result<Vec<_>, _>>()
            .map_err(|_| tdbin::EncodeError::LimitExceeded)?;
        w.len_column(at, 1, 10, &tags_counts)?;
        let tags_total = items
            .clone()
            .map(|row| row.tags.len())
            .try_fold(0_usize, usize::checked_add)
            .ok_or(tdbin::EncodeError::LimitExceeded)?;
        w.var_column(
            at,
            1,
            11,
            12,
            tags_total,
            items
                .clone()
                .flat_map(|row| row.tags.iter())
                .map(String::as_bytes),
        )?;
        Ok(())
    }

    fn read_group(
        r: &tdbin::Reader<'_>,
        at: usize,
        count: usize,
    ) -> Result<Vec<Self>, tdbin::DecodeError> {
        let mut id = r.var_column(at, 0, 1, count)?.into_strings()?.into_iter();
        let mut label = r.var_column(at, 2, 3, count)?.into_strings()?.into_iter();
        let x = r.f64_column(at, 4, count)?;
        let y = r.f64_column(at, 5, count)?;
        let width = r.f64_column(at, 6, count)?;
        let height = r.f64_column(at, 7, count)?;
        let selected = r.bit_column(at, 8, count)?;
        let locked = r.bit_column(at, 9, count)?;
        let tags_counts = r.len_column(at, 10, count)?;
        let tags_total = tdbin::column_total(&tags_counts)?;
        let mut tags = r
            .var_column(at, 11, 12, tags_total)?
            .into_strings()?
            .into_iter();
        let mut rows = Vec::with_capacity(count);
        for i in 0..count {
            let tags_take = usize::try_from(tags_counts.get(i).copied().unwrap_or(0))
                .map_err(|_| tdbin::DecodeError::LimitExceeded)?;
            rows.push(Self {
                id: id.next().ok_or(tdbin::DecodeError::MalformedColumn)?,
                label: label.next().ok_or(tdbin::DecodeError::MalformedColumn)?,
                x: x.get(i).copied().unwrap_or_default(),
                y: y.get(i).copied().unwrap_or_default(),
                width: width.get(i).copied().unwrap_or_default(),
                height: height.get(i).copied().unwrap_or_default(),
                selected: selected.get(i).copied().unwrap_or_default(),
                locked: locked.get(i).copied().unwrap_or_default(),
                tags: (0..tags_take)
                    .map(|_| tags.next().ok_or(tdbin::DecodeError::MalformedColumn))
                    .collect::<Result<Vec<_>, _>>()?,
            });
        }
        Ok(rows)
    }
}

impl tdbin::Struct for BenchEdge {
    const DATA_WORDS: u16 = 2;
    const PTR_WORDS: u16 = 4;
    const LAYOUT_HASH: u64 = 0x57d9_63de_be1d_251f;

    fn write_struct(&self, w: &mut tdbin::Writer, at: usize) -> Result<(), tdbin::EncodeError> {
        w.string(at, Self::DATA_WORDS, 0, Some(&self.id))?;
        w.string(at, Self::DATA_WORDS, 1, Some(&self.from))?;
        w.string(at, Self::DATA_WORDS, 2, Some(&self.to))?;
        w.string(at, Self::DATA_WORDS, 3, self.label.as_deref())?;
        w.scalar(at, 0, tdbin::scalar::f64_bits(self.weight))?;
        w.bool_bit(at, 1, 0, self.directed)?;
        Ok(())
    }

    fn read_struct(r: &tdbin::Reader<'_>, at: usize) -> Result<Self, tdbin::DecodeError> {
        let id = r.string(at, Self::DATA_WORDS, 0)?.unwrap_or_default();
        let from = r.string(at, Self::DATA_WORDS, 1)?.unwrap_or_default();
        let to = r.string(at, Self::DATA_WORDS, 2)?.unwrap_or_default();
        let label = r.string(at, Self::DATA_WORDS, 3)?;
        let weight = tdbin::scalar::f64_from(r.scalar(at, 0)?);
        let directed = r.bool_bit(at, 1, 0)?;
        Ok(Self {
            id,
            from,
            to,
            label,
            weight,
            directed,
        })
    }
}

impl tdbin::ColumnGroup for BenchEdge {
    const COLUMNS: u16 = 11;

    fn write_group<'v, I>(
        items: I,
        count: usize,
        w: &mut tdbin::Writer,
        at: usize,
    ) -> Result<(), tdbin::EncodeError>
    where
        I: Iterator<Item = &'v Self> + Clone,
        Self: 'v,
    {
        w.var_column(
            at,
            1,
            0,
            1,
            count,
            items.clone().map(|row| row.id.as_bytes()),
        )?;
        w.var_column(
            at,
            1,
            2,
            3,
            count,
            items.clone().map(|row| row.from.as_bytes()),
        )?;
        w.var_column(
            at,
            1,
            4,
            5,
            count,
            items.clone().map(|row| row.to.as_bytes()),
        )?;
        w.bit_column(
            at,
            1,
            6,
            count,
            items.clone().map(|row| row.label.is_some()),
        )?;
        w.var_column(
            at,
            1,
            7,
            8,
            count,
            items
                .clone()
                .map(|row| row.label.as_deref().unwrap_or_default().as_bytes()),
        )?;
        w.f64_column(at, 1, 9, count, items.clone().map(|row| row.weight))?;
        w.bit_column(at, 1, 10, count, items.clone().map(|row| row.directed))?;
        Ok(())
    }

    fn read_group(
        r: &tdbin::Reader<'_>,
        at: usize,
        count: usize,
    ) -> Result<Vec<Self>, tdbin::DecodeError> {
        let mut id = r.var_column(at, 0, 1, count)?.into_strings()?.into_iter();
        let mut from = r.var_column(at, 2, 3, count)?.into_strings()?.into_iter();
        let mut to = r.var_column(at, 4, 5, count)?.into_strings()?.into_iter();
        let label_valid = r.bit_column(at, 6, count)?;
        let label_values = r.var_column(at, 7, 8, count)?.into_strings()?;
        let mut label = label_valid
            .into_iter()
            .zip(label_values)
            .map(|(valid, value)| valid.then_some(value));
        let weight = r.f64_column(at, 9, count)?;
        let directed = r.bit_column(at, 10, count)?;
        let mut rows = Vec::with_capacity(count);
        for i in 0..count {
            rows.push(Self {
                id: id.next().ok_or(tdbin::DecodeError::MalformedColumn)?,
                from: from.next().ok_or(tdbin::DecodeError::MalformedColumn)?,
                to: to.next().ok_or(tdbin::DecodeError::MalformedColumn)?,
                label: label.next().ok_or(tdbin::DecodeError::MalformedColumn)?,
                weight: weight.get(i).copied().unwrap_or_default(),
                directed: directed.get(i).copied().unwrap_or_default(),
            });
        }
        Ok(rows)
    }
}

impl tdbin::Struct for BenchStyle {
    const DATA_WORDS: u16 = 2;
    const PTR_WORDS: u16 = 3;
    const LAYOUT_HASH: u64 = 0x2c7d_ca2b_520e_fcfe;

    fn write_struct(&self, w: &mut tdbin::Writer, at: usize) -> Result<(), tdbin::EncodeError> {
        w.string(at, Self::DATA_WORDS, 0, Some(&self.selector))?;
        w.string(at, Self::DATA_WORDS, 1, Some(&self.fill))?;
        w.string(at, Self::DATA_WORDS, 2, Some(&self.stroke))?;
        w.scalar(at, 0, tdbin::scalar::f64_bits(self.stroke_width))?;
        w.bool_bit(at, 1, 0, self.rounded)?;
        Ok(())
    }

    fn read_struct(r: &tdbin::Reader<'_>, at: usize) -> Result<Self, tdbin::DecodeError> {
        let selector = r.string(at, Self::DATA_WORDS, 0)?.unwrap_or_default();
        let fill = r.string(at, Self::DATA_WORDS, 1)?.unwrap_or_default();
        let stroke = r.string(at, Self::DATA_WORDS, 2)?.unwrap_or_default();
        let stroke_width = tdbin::scalar::f64_from(r.scalar(at, 0)?);
        let rounded = r.bool_bit(at, 1, 0)?;
        Ok(Self {
            selector,
            fill,
            stroke,
            stroke_width,
            rounded,
        })
    }
}

impl tdbin::ColumnGroup for BenchStyle {
    const COLUMNS: u16 = 8;

    fn write_group<'v, I>(
        items: I,
        count: usize,
        w: &mut tdbin::Writer,
        at: usize,
    ) -> Result<(), tdbin::EncodeError>
    where
        I: Iterator<Item = &'v Self> + Clone,
        Self: 'v,
    {
        w.var_column(
            at,
            1,
            0,
            1,
            count,
            items.clone().map(|row| row.selector.as_bytes()),
        )?;
        w.var_column(
            at,
            1,
            2,
            3,
            count,
            items.clone().map(|row| row.fill.as_bytes()),
        )?;
        w.var_column(
            at,
            1,
            4,
            5,
            count,
            items.clone().map(|row| row.stroke.as_bytes()),
        )?;
        w.f64_column(at, 1, 6, count, items.clone().map(|row| row.stroke_width))?;
        w.bit_column(at, 1, 7, count, items.clone().map(|row| row.rounded))?;
        Ok(())
    }

    fn read_group(
        r: &tdbin::Reader<'_>,
        at: usize,
        count: usize,
    ) -> Result<Vec<Self>, tdbin::DecodeError> {
        let mut selector = r.var_column(at, 0, 1, count)?.into_strings()?.into_iter();
        let mut fill = r.var_column(at, 2, 3, count)?.into_strings()?.into_iter();
        let mut stroke = r.var_column(at, 4, 5, count)?.into_strings()?.into_iter();
        let stroke_width = r.f64_column(at, 6, count)?;
        let rounded = r.bit_column(at, 7, count)?;
        let mut rows = Vec::with_capacity(count);
        for i in 0..count {
            rows.push(Self {
                selector: selector.next().ok_or(tdbin::DecodeError::MalformedColumn)?,
                fill: fill.next().ok_or(tdbin::DecodeError::MalformedColumn)?,
                stroke: stroke.next().ok_or(tdbin::DecodeError::MalformedColumn)?,
                stroke_width: stroke_width.get(i).copied().unwrap_or_default(),
                rounded: rounded.get(i).copied().unwrap_or_default(),
            });
        }
        Ok(rows)
    }
}

impl tdbin::Struct for BenchMeta {
    const DATA_WORDS: u16 = 0;
    const PTR_WORDS: u16 = 2;
    const LAYOUT_HASH: u64 = 0x6208_2e77_8f16_a7ef;

    fn write_struct(&self, w: &mut tdbin::Writer, at: usize) -> Result<(), tdbin::EncodeError> {
        w.string(at, Self::DATA_WORDS, 0, Some(&self.key))?;
        w.string(at, Self::DATA_WORDS, 1, Some(&self.value))?;
        Ok(())
    }

    fn read_struct(r: &tdbin::Reader<'_>, at: usize) -> Result<Self, tdbin::DecodeError> {
        let key = r.string(at, Self::DATA_WORDS, 0)?.unwrap_or_default();
        let value = r.string(at, Self::DATA_WORDS, 1)?.unwrap_or_default();
        Ok(Self { key, value })
    }
}

impl tdbin::ColumnGroup for BenchMeta {
    const COLUMNS: u16 = 4;

    fn write_group<'v, I>(
        items: I,
        count: usize,
        w: &mut tdbin::Writer,
        at: usize,
    ) -> Result<(), tdbin::EncodeError>
    where
        I: Iterator<Item = &'v Self> + Clone,
        Self: 'v,
    {
        w.var_column(
            at,
            1,
            0,
            1,
            count,
            items.clone().map(|row| row.key.as_bytes()),
        )?;
        w.var_column(
            at,
            1,
            2,
            3,
            count,
            items.clone().map(|row| row.value.as_bytes()),
        )?;
        Ok(())
    }

    fn read_group(
        r: &tdbin::Reader<'_>,
        at: usize,
        count: usize,
    ) -> Result<Vec<Self>, tdbin::DecodeError> {
        let mut key = r.var_column(at, 0, 1, count)?.into_strings()?.into_iter();
        let mut value = r.var_column(at, 2, 3, count)?.into_strings()?.into_iter();
        let mut rows = Vec::with_capacity(count);
        for _ in 0..count {
            rows.push(Self {
                key: key.next().ok_or(tdbin::DecodeError::MalformedColumn)?,
                value: value.next().ok_or(tdbin::DecodeError::MalformedColumn)?,
            });
        }
        Ok(rows)
    }
}

impl Default for BenchEvent {
    fn default() -> Self {
        Self::NodeCreated(BenchNodeCreated::default())
    }
}

impl tdbin::Struct for BenchEvent {
    const DATA_WORDS: u16 = 1;
    const PTR_WORDS: u16 = 1;
    const LAYOUT_HASH: u64 = 0x4c01_8979_d712_f7d7;

    fn write_struct(&self, w: &mut tdbin::Writer, at: usize) -> Result<(), tdbin::EncodeError> {
        match self {
            Self::NodeCreated(payload) => {
                w.scalar(at, 0, 0)?;
                w.child(at, Self::DATA_WORDS, 0, Some(payload))
            }
            Self::NodeMoved(payload) => {
                w.scalar(at, 0, 1)?;
                w.child(at, Self::DATA_WORDS, 0, Some(payload))
            }
            Self::EdgeAdded(payload) => {
                w.scalar(at, 0, 2)?;
                w.child(at, Self::DATA_WORDS, 0, Some(payload))
            }
            Self::SelectionChanged(payload) => {
                w.scalar(at, 0, 3)?;
                w.child(at, Self::DATA_WORDS, 0, Some(payload))
            }
            Self::ViewChanged(payload) => {
                w.scalar(at, 0, 4)?;
                w.child(at, Self::DATA_WORDS, 0, Some(payload))
            }
            Self::Heartbeat => {
                w.scalar(at, 0, 5)?;
                Ok(())
            }
        }
    }

    fn read_struct(r: &tdbin::Reader<'_>, at: usize) -> Result<Self, tdbin::DecodeError> {
        match r.scalar(at, 0)? {
            0 => Ok(Self::NodeCreated(
                r.child::<BenchNodeCreated>(at, Self::DATA_WORDS, 0)?
                    .unwrap_or_default(),
            )),
            1 => Ok(Self::NodeMoved(
                r.child::<BenchNodeMoved>(at, Self::DATA_WORDS, 0)?
                    .unwrap_or_default(),
            )),
            2 => Ok(Self::EdgeAdded(
                r.child::<BenchEdgeAdded>(at, Self::DATA_WORDS, 0)?
                    .unwrap_or_default(),
            )),
            3 => Ok(Self::SelectionChanged(
                r.child::<BenchSelectionChanged>(at, Self::DATA_WORDS, 0)?
                    .unwrap_or_default(),
            )),
            4 => Ok(Self::ViewChanged(
                r.child::<BenchViewChanged>(at, Self::DATA_WORDS, 0)?
                    .unwrap_or_default(),
            )),
            5 => {
                r.require_null_pointer(at, 0)?;
                Ok(Self::Heartbeat)
            }
            ordinal => {
                r.verify_struct_slots(at)?;
                Err(tdbin::DecodeError::UnknownVariant { ordinal })
            }
        }
    }
}

impl tdbin::ColumnGroup for BenchEvent {
    const COLUMNS: u16 = 6;

    fn write_group<'v, I>(
        items: I,
        count: usize,
        w: &mut tdbin::Writer,
        at: usize,
    ) -> Result<(), tdbin::EncodeError>
    where
        I: Iterator<Item = &'v Self> + Clone,
        Self: 'v,
    {
        w.byte_column(
            at,
            1,
            0,
            count,
            items.clone().map(|row| match row {
                Self::NodeCreated(_) => 0_u8,
                Self::NodeMoved(_) => 1_u8,
                Self::EdgeAdded(_) => 2_u8,
                Self::SelectionChanged(_) => 3_u8,
                Self::ViewChanged(_) => 4_u8,
                Self::Heartbeat => 5_u8,
            }),
        )?;
        let node_created: Vec<&BenchNodeCreated> = items
            .clone()
            .filter_map(|row| match row {
                Self::NodeCreated(payload) => Some(payload),
                Self::NodeMoved(_)
                | Self::EdgeAdded(_)
                | Self::SelectionChanged(_)
                | Self::ViewChanged(_)
                | Self::Heartbeat => None,
            })
            .collect();
        w.dense_group(at, 1, 1, node_created.len(), node_created.iter().copied())?;
        let node_moved: Vec<&BenchNodeMoved> = items
            .clone()
            .filter_map(|row| match row {
                Self::NodeMoved(payload) => Some(payload),
                Self::NodeCreated(_)
                | Self::EdgeAdded(_)
                | Self::SelectionChanged(_)
                | Self::ViewChanged(_)
                | Self::Heartbeat => None,
            })
            .collect();
        w.dense_group(at, 1, 2, node_moved.len(), node_moved.iter().copied())?;
        let edge_added: Vec<&BenchEdgeAdded> = items
            .clone()
            .filter_map(|row| match row {
                Self::EdgeAdded(payload) => Some(payload),
                Self::NodeCreated(_)
                | Self::NodeMoved(_)
                | Self::SelectionChanged(_)
                | Self::ViewChanged(_)
                | Self::Heartbeat => None,
            })
            .collect();
        w.dense_group(at, 1, 3, edge_added.len(), edge_added.iter().copied())?;
        let selection_changed: Vec<&BenchSelectionChanged> = items
            .clone()
            .filter_map(|row| match row {
                Self::SelectionChanged(payload) => Some(payload),
                Self::NodeCreated(_)
                | Self::NodeMoved(_)
                | Self::EdgeAdded(_)
                | Self::ViewChanged(_)
                | Self::Heartbeat => None,
            })
            .collect();
        w.dense_group(
            at,
            1,
            4,
            selection_changed.len(),
            selection_changed.iter().copied(),
        )?;
        let view_changed: Vec<&BenchViewChanged> = items
            .clone()
            .filter_map(|row| match row {
                Self::ViewChanged(payload) => Some(payload),
                Self::NodeCreated(_)
                | Self::NodeMoved(_)
                | Self::EdgeAdded(_)
                | Self::SelectionChanged(_)
                | Self::Heartbeat => None,
            })
            .collect();
        w.dense_group(at, 1, 5, view_changed.len(), view_changed.iter().copied())?;
        Ok(())
    }

    fn read_group(
        r: &tdbin::Reader<'_>,
        at: usize,
        count: usize,
    ) -> Result<Vec<Self>, tdbin::DecodeError> {
        let tags = r.byte_column(at, 0, count)?;
        let node_created_count = tags.iter().map(|tag| usize::from(*tag == 0)).sum::<usize>();
        let mut node_created = r
            .dense_group::<BenchNodeCreated>(at, 1, node_created_count)?
            .into_iter();
        let node_moved_count = tags.iter().map(|tag| usize::from(*tag == 1)).sum::<usize>();
        let mut node_moved = r
            .dense_group::<BenchNodeMoved>(at, 2, node_moved_count)?
            .into_iter();
        let edge_added_count = tags.iter().map(|tag| usize::from(*tag == 2)).sum::<usize>();
        let mut edge_added = r
            .dense_group::<BenchEdgeAdded>(at, 3, edge_added_count)?
            .into_iter();
        let selection_changed_count = tags.iter().map(|tag| usize::from(*tag == 3)).sum::<usize>();
        let mut selection_changed = r
            .dense_group::<BenchSelectionChanged>(at, 4, selection_changed_count)?
            .into_iter();
        let view_changed_count = tags.iter().map(|tag| usize::from(*tag == 4)).sum::<usize>();
        let mut view_changed = r
            .dense_group::<BenchViewChanged>(at, 5, view_changed_count)?
            .into_iter();
        let mut rows = Vec::with_capacity(count);
        for tag in tags {
            rows.push(match tag {
                0 => Self::NodeCreated(
                    node_created
                        .next()
                        .ok_or(tdbin::DecodeError::MalformedColumn)?,
                ),
                1 => Self::NodeMoved(
                    node_moved
                        .next()
                        .ok_or(tdbin::DecodeError::MalformedColumn)?,
                ),
                2 => Self::EdgeAdded(
                    edge_added
                        .next()
                        .ok_or(tdbin::DecodeError::MalformedColumn)?,
                ),
                3 => Self::SelectionChanged(
                    selection_changed
                        .next()
                        .ok_or(tdbin::DecodeError::MalformedColumn)?,
                ),
                4 => Self::ViewChanged(
                    view_changed
                        .next()
                        .ok_or(tdbin::DecodeError::MalformedColumn)?,
                ),
                5 => Self::Heartbeat,
                ordinal => {
                    return Err(tdbin::DecodeError::UnknownVariant {
                        ordinal: u64::from(ordinal),
                    });
                }
            });
        }
        Ok(rows)
    }
}

impl tdbin::Struct for BenchEventBatch {
    const DATA_WORDS: u16 = 0;
    const PTR_WORDS: u16 = 1;
    const LAYOUT_HASH: u64 = 0xf86f_283a_5a72_0f7f;

    fn write_struct(&self, w: &mut tdbin::Writer, at: usize) -> Result<(), tdbin::EncodeError> {
        w.column_list(at, Self::DATA_WORDS, 0, Some(&self.events))?;
        Ok(())
    }

    fn read_struct(r: &tdbin::Reader<'_>, at: usize) -> Result<Self, tdbin::DecodeError> {
        let events = r
            .column_list::<BenchEvent>(at, Self::DATA_WORDS, 0)?
            .unwrap_or_default();
        Ok(Self { events })
    }
}

impl tdbin::Struct for BenchNodeCreated {
    const DATA_WORDS: u16 = 0;
    const PTR_WORDS: u16 = 2;
    const LAYOUT_HASH: u64 = 0xa3a2_2c90_db9f_3cbc;

    fn write_struct(&self, w: &mut tdbin::Writer, at: usize) -> Result<(), tdbin::EncodeError> {
        w.string(at, Self::DATA_WORDS, 0, Some(&self.document_id))?;
        w.child(at, Self::DATA_WORDS, 1, Some(&self.node))?;
        Ok(())
    }

    fn read_struct(r: &tdbin::Reader<'_>, at: usize) -> Result<Self, tdbin::DecodeError> {
        let document_id = r.string(at, Self::DATA_WORDS, 0)?.unwrap_or_default();
        let node = r
            .child::<BenchNode>(at, Self::DATA_WORDS, 1)?
            .unwrap_or_default();
        Ok(Self { document_id, node })
    }
}

impl tdbin::ColumnGroup for BenchNodeCreated {
    const COLUMNS: u16 = 3;

    fn write_group<'v, I>(
        items: I,
        count: usize,
        w: &mut tdbin::Writer,
        at: usize,
    ) -> Result<(), tdbin::EncodeError>
    where
        I: Iterator<Item = &'v Self> + Clone,
        Self: 'v,
    {
        w.var_column(
            at,
            1,
            0,
            1,
            count,
            items.clone().map(|row| row.document_id.as_bytes()),
        )?;
        w.dense_group(at, 1, 2, count, items.clone().map(|row| &row.node))?;
        Ok(())
    }

    fn read_group(
        r: &tdbin::Reader<'_>,
        at: usize,
        count: usize,
    ) -> Result<Vec<Self>, tdbin::DecodeError> {
        let mut document_id = r.var_column(at, 0, 1, count)?.into_strings()?.into_iter();
        let mut node = r.dense_group::<BenchNode>(at, 2, count)?.into_iter();
        let mut rows = Vec::with_capacity(count);
        for _ in 0..count {
            rows.push(Self {
                document_id: document_id
                    .next()
                    .ok_or(tdbin::DecodeError::MalformedColumn)?,
                node: node.next().ok_or(tdbin::DecodeError::MalformedColumn)?,
            });
        }
        Ok(rows)
    }
}

impl tdbin::Struct for BenchNodeMoved {
    const DATA_WORDS: u16 = 2;
    const PTR_WORDS: u16 = 2;
    const LAYOUT_HASH: u64 = 0x74f6_e02d_b006_6128;

    fn write_struct(&self, w: &mut tdbin::Writer, at: usize) -> Result<(), tdbin::EncodeError> {
        w.string(at, Self::DATA_WORDS, 0, Some(&self.document_id))?;
        w.string(at, Self::DATA_WORDS, 1, Some(&self.node_id))?;
        w.scalar(at, 0, tdbin::scalar::f64_bits(self.x))?;
        w.scalar(at, 1, tdbin::scalar::f64_bits(self.y))?;
        Ok(())
    }

    fn read_struct(r: &tdbin::Reader<'_>, at: usize) -> Result<Self, tdbin::DecodeError> {
        let document_id = r.string(at, Self::DATA_WORDS, 0)?.unwrap_or_default();
        let node_id = r.string(at, Self::DATA_WORDS, 1)?.unwrap_or_default();
        let x = tdbin::scalar::f64_from(r.scalar(at, 0)?);
        let y = tdbin::scalar::f64_from(r.scalar(at, 1)?);
        Ok(Self {
            document_id,
            node_id,
            x,
            y,
        })
    }
}

impl tdbin::ColumnGroup for BenchNodeMoved {
    const COLUMNS: u16 = 6;

    fn write_group<'v, I>(
        items: I,
        count: usize,
        w: &mut tdbin::Writer,
        at: usize,
    ) -> Result<(), tdbin::EncodeError>
    where
        I: Iterator<Item = &'v Self> + Clone,
        Self: 'v,
    {
        w.var_column(
            at,
            1,
            0,
            1,
            count,
            items.clone().map(|row| row.document_id.as_bytes()),
        )?;
        w.var_column(
            at,
            1,
            2,
            3,
            count,
            items.clone().map(|row| row.node_id.as_bytes()),
        )?;
        w.f64_column(at, 1, 4, count, items.clone().map(|row| row.x))?;
        w.f64_column(at, 1, 5, count, items.clone().map(|row| row.y))?;
        Ok(())
    }

    fn read_group(
        r: &tdbin::Reader<'_>,
        at: usize,
        count: usize,
    ) -> Result<Vec<Self>, tdbin::DecodeError> {
        let mut document_id = r.var_column(at, 0, 1, count)?.into_strings()?.into_iter();
        let mut node_id = r.var_column(at, 2, 3, count)?.into_strings()?.into_iter();
        let x = r.f64_column(at, 4, count)?;
        let y = r.f64_column(at, 5, count)?;
        let mut rows = Vec::with_capacity(count);
        for i in 0..count {
            rows.push(Self {
                document_id: document_id
                    .next()
                    .ok_or(tdbin::DecodeError::MalformedColumn)?,
                node_id: node_id.next().ok_or(tdbin::DecodeError::MalformedColumn)?,
                x: x.get(i).copied().unwrap_or_default(),
                y: y.get(i).copied().unwrap_or_default(),
            });
        }
        Ok(rows)
    }
}

impl tdbin::Struct for BenchEdgeAdded {
    const DATA_WORDS: u16 = 0;
    const PTR_WORDS: u16 = 2;
    const LAYOUT_HASH: u64 = 0x3c88_357d_f2e0_e8e2;

    fn write_struct(&self, w: &mut tdbin::Writer, at: usize) -> Result<(), tdbin::EncodeError> {
        w.string(at, Self::DATA_WORDS, 0, Some(&self.document_id))?;
        w.child(at, Self::DATA_WORDS, 1, Some(&self.edge))?;
        Ok(())
    }

    fn read_struct(r: &tdbin::Reader<'_>, at: usize) -> Result<Self, tdbin::DecodeError> {
        let document_id = r.string(at, Self::DATA_WORDS, 0)?.unwrap_or_default();
        let edge = r
            .child::<BenchEdge>(at, Self::DATA_WORDS, 1)?
            .unwrap_or_default();
        Ok(Self { document_id, edge })
    }
}

impl tdbin::ColumnGroup for BenchEdgeAdded {
    const COLUMNS: u16 = 3;

    fn write_group<'v, I>(
        items: I,
        count: usize,
        w: &mut tdbin::Writer,
        at: usize,
    ) -> Result<(), tdbin::EncodeError>
    where
        I: Iterator<Item = &'v Self> + Clone,
        Self: 'v,
    {
        w.var_column(
            at,
            1,
            0,
            1,
            count,
            items.clone().map(|row| row.document_id.as_bytes()),
        )?;
        w.dense_group(at, 1, 2, count, items.clone().map(|row| &row.edge))?;
        Ok(())
    }

    fn read_group(
        r: &tdbin::Reader<'_>,
        at: usize,
        count: usize,
    ) -> Result<Vec<Self>, tdbin::DecodeError> {
        let mut document_id = r.var_column(at, 0, 1, count)?.into_strings()?.into_iter();
        let mut edge = r.dense_group::<BenchEdge>(at, 2, count)?.into_iter();
        let mut rows = Vec::with_capacity(count);
        for _ in 0..count {
            rows.push(Self {
                document_id: document_id
                    .next()
                    .ok_or(tdbin::DecodeError::MalformedColumn)?,
                edge: edge.next().ok_or(tdbin::DecodeError::MalformedColumn)?,
            });
        }
        Ok(rows)
    }
}

impl tdbin::Struct for BenchSelectionChanged {
    const DATA_WORDS: u16 = 0;
    const PTR_WORDS: u16 = 5;
    const LAYOUT_HASH: u64 = 0x036c_a49f_3778_8b59;

    fn write_struct(&self, w: &mut tdbin::Writer, at: usize) -> Result<(), tdbin::EncodeError> {
        w.string(at, Self::DATA_WORDS, 0, Some(&self.document_id))?;
        w.string_var_list(at, Self::DATA_WORDS, 1, 2, Some(&self.node_ids))?;
        w.string_var_list(at, Self::DATA_WORDS, 3, 4, Some(&self.edge_ids))?;
        Ok(())
    }

    fn read_struct(r: &tdbin::Reader<'_>, at: usize) -> Result<Self, tdbin::DecodeError> {
        let document_id = r.string(at, Self::DATA_WORDS, 0)?.unwrap_or_default();
        let node_ids = match r.var_list(at, Self::DATA_WORDS, 1, 2)? {
            Some(column) => column.into_strings()?,
            None => Vec::new(),
        };
        let edge_ids = match r.var_list(at, Self::DATA_WORDS, 3, 4)? {
            Some(column) => column.into_strings()?,
            None => Vec::new(),
        };
        Ok(Self {
            document_id,
            node_ids,
            edge_ids,
        })
    }
}

impl tdbin::ColumnGroup for BenchSelectionChanged {
    const COLUMNS: u16 = 8;

    fn write_group<'v, I>(
        items: I,
        count: usize,
        w: &mut tdbin::Writer,
        at: usize,
    ) -> Result<(), tdbin::EncodeError>
    where
        I: Iterator<Item = &'v Self> + Clone,
        Self: 'v,
    {
        w.var_column(
            at,
            1,
            0,
            1,
            count,
            items.clone().map(|row| row.document_id.as_bytes()),
        )?;
        let node_ids_counts = items
            .clone()
            .map(|row| u32::try_from(row.node_ids.len()))
            .collect::<Result<Vec<_>, _>>()
            .map_err(|_| tdbin::EncodeError::LimitExceeded)?;
        w.len_column(at, 1, 2, &node_ids_counts)?;
        let node_ids_total = items
            .clone()
            .map(|row| row.node_ids.len())
            .try_fold(0_usize, usize::checked_add)
            .ok_or(tdbin::EncodeError::LimitExceeded)?;
        w.var_column(
            at,
            1,
            3,
            4,
            node_ids_total,
            items
                .clone()
                .flat_map(|row| row.node_ids.iter())
                .map(String::as_bytes),
        )?;
        let edge_ids_counts = items
            .clone()
            .map(|row| u32::try_from(row.edge_ids.len()))
            .collect::<Result<Vec<_>, _>>()
            .map_err(|_| tdbin::EncodeError::LimitExceeded)?;
        w.len_column(at, 1, 5, &edge_ids_counts)?;
        let edge_ids_total = items
            .clone()
            .map(|row| row.edge_ids.len())
            .try_fold(0_usize, usize::checked_add)
            .ok_or(tdbin::EncodeError::LimitExceeded)?;
        w.var_column(
            at,
            1,
            6,
            7,
            edge_ids_total,
            items
                .clone()
                .flat_map(|row| row.edge_ids.iter())
                .map(String::as_bytes),
        )?;
        Ok(())
    }

    fn read_group(
        r: &tdbin::Reader<'_>,
        at: usize,
        count: usize,
    ) -> Result<Vec<Self>, tdbin::DecodeError> {
        let mut document_id = r.var_column(at, 0, 1, count)?.into_strings()?.into_iter();
        let node_ids_counts = r.len_column(at, 2, count)?;
        let node_ids_total = tdbin::column_total(&node_ids_counts)?;
        let mut node_ids = r
            .var_column(at, 3, 4, node_ids_total)?
            .into_strings()?
            .into_iter();
        let edge_ids_counts = r.len_column(at, 5, count)?;
        let edge_ids_total = tdbin::column_total(&edge_ids_counts)?;
        let mut edge_ids = r
            .var_column(at, 6, 7, edge_ids_total)?
            .into_strings()?
            .into_iter();
        let mut rows = Vec::with_capacity(count);
        for i in 0..count {
            let node_ids_take = usize::try_from(node_ids_counts.get(i).copied().unwrap_or(0))
                .map_err(|_| tdbin::DecodeError::LimitExceeded)?;
            let edge_ids_take = usize::try_from(edge_ids_counts.get(i).copied().unwrap_or(0))
                .map_err(|_| tdbin::DecodeError::LimitExceeded)?;
            rows.push(Self {
                document_id: document_id
                    .next()
                    .ok_or(tdbin::DecodeError::MalformedColumn)?,
                node_ids: (0..node_ids_take)
                    .map(|_| node_ids.next().ok_or(tdbin::DecodeError::MalformedColumn))
                    .collect::<Result<Vec<_>, _>>()?,
                edge_ids: (0..edge_ids_take)
                    .map(|_| edge_ids.next().ok_or(tdbin::DecodeError::MalformedColumn))
                    .collect::<Result<Vec<_>, _>>()?,
            });
        }
        Ok(rows)
    }
}

impl tdbin::Struct for BenchViewChanged {
    const DATA_WORDS: u16 = 3;
    const PTR_WORDS: u16 = 1;
    const LAYOUT_HASH: u64 = 0xdd8f_7d40_1a67_50bd;

    fn write_struct(&self, w: &mut tdbin::Writer, at: usize) -> Result<(), tdbin::EncodeError> {
        w.string(at, Self::DATA_WORDS, 0, Some(&self.document_id))?;
        w.scalar(at, 0, tdbin::scalar::f64_bits(self.zoom))?;
        w.scalar(at, 1, tdbin::scalar::f64_bits(self.offset_x))?;
        w.scalar(at, 2, tdbin::scalar::f64_bits(self.offset_y))?;
        Ok(())
    }

    fn read_struct(r: &tdbin::Reader<'_>, at: usize) -> Result<Self, tdbin::DecodeError> {
        let document_id = r.string(at, Self::DATA_WORDS, 0)?.unwrap_or_default();
        let zoom = tdbin::scalar::f64_from(r.scalar(at, 0)?);
        let offset_x = tdbin::scalar::f64_from(r.scalar(at, 1)?);
        let offset_y = tdbin::scalar::f64_from(r.scalar(at, 2)?);
        Ok(Self {
            document_id,
            zoom,
            offset_x,
            offset_y,
        })
    }
}

impl tdbin::ColumnGroup for BenchViewChanged {
    const COLUMNS: u16 = 5;

    fn write_group<'v, I>(
        items: I,
        count: usize,
        w: &mut tdbin::Writer,
        at: usize,
    ) -> Result<(), tdbin::EncodeError>
    where
        I: Iterator<Item = &'v Self> + Clone,
        Self: 'v,
    {
        w.var_column(
            at,
            1,
            0,
            1,
            count,
            items.clone().map(|row| row.document_id.as_bytes()),
        )?;
        w.f64_column(at, 1, 2, count, items.clone().map(|row| row.zoom))?;
        w.f64_column(at, 1, 3, count, items.clone().map(|row| row.offset_x))?;
        w.f64_column(at, 1, 4, count, items.clone().map(|row| row.offset_y))?;
        Ok(())
    }

    fn read_group(
        r: &tdbin::Reader<'_>,
        at: usize,
        count: usize,
    ) -> Result<Vec<Self>, tdbin::DecodeError> {
        let mut document_id = r.var_column(at, 0, 1, count)?.into_strings()?.into_iter();
        let zoom = r.f64_column(at, 2, count)?;
        let offset_x = r.f64_column(at, 3, count)?;
        let offset_y = r.f64_column(at, 4, count)?;
        let mut rows = Vec::with_capacity(count);
        for i in 0..count {
            rows.push(Self {
                document_id: document_id
                    .next()
                    .ok_or(tdbin::DecodeError::MalformedColumn)?,
                zoom: zoom.get(i).copied().unwrap_or_default(),
                offset_x: offset_x.get(i).copied().unwrap_or_default(),
                offset_y: offset_y.get(i).copied().unwrap_or_default(),
            });
        }
        Ok(rows)
    }
}

impl tdbin::Struct for BenchMetricBatch {
    const DATA_WORDS: u16 = 1;
    const PTR_WORDS: u16 = 7;
    const LAYOUT_HASH: u64 = 0x24e1_dc71_6e37_989f;

    fn write_struct(&self, w: &mut tdbin::Writer, at: usize) -> Result<(), tdbin::EncodeError> {
        w.string(at, Self::DATA_WORDS, 0, Some(&self.batch_id))?;
        w.scalar(at, 0, tdbin::scalar::i64_bits(self.started_at_epoch_ms))?;
        w.i64_block_list(at, Self::DATA_WORDS, 1, Some(&self.sample_ids))?;
        w.bool_list(at, Self::DATA_WORDS, 2, Some(&self.valid))?;
        w.f64_list(at, Self::DATA_WORDS, 3, Some(&self.latency_ms))?;
        w.bytes_var_list(at, Self::DATA_WORDS, 4, 5, Some(&self.payloads))?;
        w.column_list(at, Self::DATA_WORDS, 6, Some(&self.columns))?;
        Ok(())
    }

    fn read_struct(r: &tdbin::Reader<'_>, at: usize) -> Result<Self, tdbin::DecodeError> {
        let batch_id = r.string(at, Self::DATA_WORDS, 0)?.unwrap_or_default();
        let started_at_epoch_ms = tdbin::scalar::i64_from(r.scalar(at, 0)?);
        let sample_ids = r
            .i64_block_list(at, Self::DATA_WORDS, 1)?
            .unwrap_or_default();
        let valid = r.bool_list(at, Self::DATA_WORDS, 2)?.unwrap_or_default();
        let latency_ms = r.f64_list(at, Self::DATA_WORDS, 3)?.unwrap_or_default();
        let payloads = match r.var_list(at, Self::DATA_WORDS, 4, 5)? {
            Some(column) => column.into_byte_vecs()?,
            None => Vec::new(),
        };
        let columns = r
            .column_list::<BenchMetricColumn>(at, Self::DATA_WORDS, 6)?
            .unwrap_or_default();
        Ok(Self {
            batch_id,
            started_at_epoch_ms,
            sample_ids,
            valid,
            latency_ms,
            payloads,
            columns,
        })
    }
}

impl tdbin::Struct for BenchMetricColumn {
    const DATA_WORDS: u16 = 0;
    const PTR_WORDS: u16 = 2;
    const LAYOUT_HASH: u64 = 0x38b8_b754_3c03_df8f;

    fn write_struct(&self, w: &mut tdbin::Writer, at: usize) -> Result<(), tdbin::EncodeError> {
        w.string(at, Self::DATA_WORDS, 0, Some(&self.name))?;
        w.f64_list(at, Self::DATA_WORDS, 1, Some(&self.values))?;
        Ok(())
    }

    fn read_struct(r: &tdbin::Reader<'_>, at: usize) -> Result<Self, tdbin::DecodeError> {
        let name = r.string(at, Self::DATA_WORDS, 0)?.unwrap_or_default();
        let values = r.f64_list(at, Self::DATA_WORDS, 1)?.unwrap_or_default();
        Ok(Self { name, values })
    }
}

impl tdbin::ColumnGroup for BenchMetricColumn {
    const COLUMNS: u16 = 4;

    fn write_group<'v, I>(
        items: I,
        count: usize,
        w: &mut tdbin::Writer,
        at: usize,
    ) -> Result<(), tdbin::EncodeError>
    where
        I: Iterator<Item = &'v Self> + Clone,
        Self: 'v,
    {
        w.var_column(
            at,
            1,
            0,
            1,
            count,
            items.clone().map(|row| row.name.as_bytes()),
        )?;
        let values_counts = items
            .clone()
            .map(|row| u32::try_from(row.values.len()))
            .collect::<Result<Vec<_>, _>>()
            .map_err(|_| tdbin::EncodeError::LimitExceeded)?;
        w.len_column(at, 1, 2, &values_counts)?;
        let values_total = items
            .clone()
            .map(|row| row.values.len())
            .try_fold(0_usize, usize::checked_add)
            .ok_or(tdbin::EncodeError::LimitExceeded)?;
        w.f64_column(
            at,
            1,
            3,
            values_total,
            items.clone().flat_map(|row| row.values.iter()).copied(),
        )?;
        Ok(())
    }

    fn read_group(
        r: &tdbin::Reader<'_>,
        at: usize,
        count: usize,
    ) -> Result<Vec<Self>, tdbin::DecodeError> {
        let mut name = r.var_column(at, 0, 1, count)?.into_strings()?.into_iter();
        let values_counts = r.len_column(at, 2, count)?;
        let values_total = tdbin::column_total(&values_counts)?;
        let mut values = r.f64_column(at, 3, values_total)?.into_iter();
        let mut rows = Vec::with_capacity(count);
        for i in 0..count {
            let values_take = usize::try_from(values_counts.get(i).copied().unwrap_or(0))
                .map_err(|_| tdbin::DecodeError::LimitExceeded)?;
            rows.push(Self {
                name: name.next().ok_or(tdbin::DecodeError::MalformedColumn)?,
                values: (0..values_take)
                    .map(|_| values.next().ok_or(tdbin::DecodeError::MalformedColumn))
                    .collect::<Result<Vec<_>, _>>()?,
            });
        }
        Ok(rows)
    }
}
