#!/bin/sh
# [VSCODE-E2E-DARWIN-LAUNCHER] Start the GUI binary without inherited extension-host mode.
unset ELECTRON_RUN_AS_NODE
unset VSCODE_CODE_CACHE_PATH VSCODE_CRASH_REPORTER_PROCESS_TYPE VSCODE_CWD
unset VSCODE_ESM_ENTRYPOINT VSCODE_HANDLES_UNCAUGHT_ERRORS VSCODE_IPC_HOOK VSCODE_NLS_CONFIG VSCODE_PID
exec "${TYPEDIAGRAM_VSCODE_APP_PATH:?}/Contents/MacOS/Code" "$@"
