//! [TDBIN-BENCH-CORPUS] typeDiagram ADT + TDBIN columnar codec (layout major
//! 2), GENERATED by `packages/typediagram/src/converters/rust-tdbin.ts`
//! (`generateRustModule(model, { layout: 2 })`) from the Person/PersonBatch/
//! ContactBatch schema in
//! `packages/typediagram/test/converters/fixtures/batches.td`. The benchmark
//! support fixtures consume these types. The `rust-tdbin-corpus.test.ts`
//! vitest suite pins the emitted text and fails if this file drifts from
//! codegen; regenerate with `node scripts/tdbin-regen-fixtures.mjs` rather
//! than hand-editing.

// <<<GENERATED — rust-tdbin.ts generateRustModule (layout 2); do not edit by hand>>>
/// The `Person` record.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct Person {
    /// The `name` field.
    pub name: String,
    /// The `age` field.
    pub age: i64,
    /// The `active` field.
    pub active: bool,
    /// The `score` field.
    pub score: f64,
    /// The `address` field.
    pub address: Option<Address>,
    /// The `nickname` field.
    pub nickname: Option<String>,
    /// The `contact` field.
    pub contact: Contact,
}

/// The `Address` record.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct Address {
    /// The `street` field.
    pub street: String,
    /// The `zip` field.
    pub zip: i64,
}

/// The `Contact` union.
#[derive(Debug, Clone, PartialEq)]
pub enum Contact {
    /// The `Email` variant.
    Email(EmailContact),
    /// The `Phone` variant.
    Phone(PhoneContact),
}

/// The `EmailContact` record.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct EmailContact {
    /// The `addr` field.
    pub addr: String,
}

/// The `PhoneContact` record.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct PhoneContact {
    /// The `number` field.
    pub number: i64,
    /// The `country` field.
    pub country: i64,
}

/// The `PersonBatch` record.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct PersonBatch {
    /// The `people` field.
    pub people: Vec<Person>,
}

/// The `ContactBatch` record.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct ContactBatch {
    /// The `contacts` field.
    pub contacts: Vec<Contact>,
}

impl tdbin::Struct for Person {
    const DATA_WORDS: u16 = 3;
    const PTR_WORDS: u16 = 4;
    const LAYOUT_HASH: u64 = 0xacae_50bb_da61_6ed3;

    fn write_struct(&self, w: &mut tdbin::Writer, at: usize) -> Result<(), tdbin::EncodeError> {
        w.string(at, Self::DATA_WORDS, 0, Some(&self.name))?;
        w.scalar(at, 0, tdbin::scalar::i64_bits(self.age))?;
        w.bool_bit(at, 1, 0, self.active)?;
        w.scalar(at, 2, tdbin::scalar::f64_bits(self.score))?;
        w.child(at, Self::DATA_WORDS, 1, self.address.as_ref())?;
        w.string(at, Self::DATA_WORDS, 2, self.nickname.as_deref())?;
        w.child(at, Self::DATA_WORDS, 3, Some(&self.contact))?;
        Ok(())
    }

    fn read_struct(r: &tdbin::Reader<'_>, at: usize) -> Result<Self, tdbin::DecodeError> {
        let name = r.string(at, Self::DATA_WORDS, 0)?.unwrap_or_default();
        let age = tdbin::scalar::i64_from(r.scalar(at, 0)?);
        let active = r.bool_bit(at, 1, 0)?;
        let score = tdbin::scalar::f64_from(r.scalar(at, 2)?);
        let address = r.child::<Address>(at, Self::DATA_WORDS, 1)?;
        let nickname = r.string(at, Self::DATA_WORDS, 2)?;
        let contact = r
            .child::<Contact>(at, Self::DATA_WORDS, 3)?
            .unwrap_or_default();
        Ok(Self {
            name,
            age,
            active,
            score,
            address,
            nickname,
            contact,
        })
    }
}

impl tdbin::ColumnGroup for Person {
    const COLUMNS: u16 = 11;

    fn write_group<'v, I>(
        items: I,
        count: usize,
        w: &mut tdbin::Writer,
        at: usize,
    ) -> Result<(), tdbin::EncodeError>
    where
        I: Iterator<Item = &'v Self> + Clone,
        Self: 'v,
    {
        w.var_column(
            at,
            1,
            0,
            1,
            count,
            items.clone().map(|row| row.name.as_bytes()),
        )?;
        w.i64_block_column(at, 1, 2, count, items.clone().map(|row| row.age))?;
        w.bit_column(at, 1, 3, count, items.clone().map(|row| row.active))?;
        w.f64_column(at, 1, 4, count, items.clone().map(|row| row.score))?;
        w.bit_column(
            at,
            1,
            5,
            count,
            items.clone().map(|row| row.address.is_some()),
        )?;
        let address: Vec<&Address> = items
            .clone()
            .filter_map(|row| row.address.as_ref())
            .collect();
        w.dense_group(at, 1, 6, address.len(), address.iter().copied())?;
        w.bit_column(
            at,
            1,
            7,
            count,
            items.clone().map(|row| row.nickname.is_some()),
        )?;
        w.var_column(
            at,
            1,
            8,
            9,
            count,
            items
                .clone()
                .map(|row| row.nickname.as_deref().unwrap_or_default().as_bytes()),
        )?;
        w.dense_group(at, 1, 10, count, items.clone().map(|row| &row.contact))?;
        Ok(())
    }

    fn read_group(
        r: &tdbin::Reader<'_>,
        at: usize,
        count: usize,
    ) -> Result<Vec<Self>, tdbin::DecodeError> {
        let mut name = r.var_column(at, 0, 1, count)?.into_strings()?.into_iter();
        let age = r.i64_block_column(at, 2, count)?;
        let active = r.bit_column(at, 3, count)?;
        let score = r.f64_column(at, 4, count)?;
        let address_valid = r.bit_column(at, 5, count)?;
        let address_count = address_valid.iter().filter(|present| **present).count();
        let mut address = r.dense_group::<Address>(at, 6, address_count)?.into_iter();
        let nickname_valid = r.bit_column(at, 7, count)?;
        let nickname_values = r.var_column(at, 8, 9, count)?.into_strings()?;
        let mut nickname = nickname_valid
            .into_iter()
            .zip(nickname_values)
            .map(|(valid, value)| valid.then_some(value));
        let mut contact = r.dense_group::<Contact>(at, 10, count)?.into_iter();
        let mut rows = Vec::with_capacity(count);
        for i in 0..count {
            rows.push(Self {
                name: name.next().ok_or(tdbin::DecodeError::MalformedColumn)?,
                age: age.get(i).copied().unwrap_or_default(),
                active: active.get(i).copied().unwrap_or_default(),
                score: score.get(i).copied().unwrap_or_default(),
                address: address_valid
                    .get(i)
                    .copied()
                    .unwrap_or_default()
                    .then(|| address.next().ok_or(tdbin::DecodeError::MalformedColumn))
                    .transpose()?,
                nickname: nickname.next().ok_or(tdbin::DecodeError::MalformedColumn)?,
                contact: contact.next().ok_or(tdbin::DecodeError::MalformedColumn)?,
            });
        }
        Ok(rows)
    }
}

impl tdbin::Struct for Address {
    const DATA_WORDS: u16 = 1;
    const PTR_WORDS: u16 = 1;
    const LAYOUT_HASH: u64 = 0x389e_f7e5_34b9_dacb;

    fn write_struct(&self, w: &mut tdbin::Writer, at: usize) -> Result<(), tdbin::EncodeError> {
        w.string(at, Self::DATA_WORDS, 0, Some(&self.street))?;
        w.scalar(at, 0, tdbin::scalar::i64_bits(self.zip))?;
        Ok(())
    }

    fn read_struct(r: &tdbin::Reader<'_>, at: usize) -> Result<Self, tdbin::DecodeError> {
        let street = r.string(at, Self::DATA_WORDS, 0)?.unwrap_or_default();
        let zip = tdbin::scalar::i64_from(r.scalar(at, 0)?);
        Ok(Self { street, zip })
    }
}

impl tdbin::ColumnGroup for Address {
    const COLUMNS: u16 = 3;

    fn write_group<'v, I>(
        items: I,
        count: usize,
        w: &mut tdbin::Writer,
        at: usize,
    ) -> Result<(), tdbin::EncodeError>
    where
        I: Iterator<Item = &'v Self> + Clone,
        Self: 'v,
    {
        w.var_column(
            at,
            1,
            0,
            1,
            count,
            items.clone().map(|row| row.street.as_bytes()),
        )?;
        w.i64_block_column(at, 1, 2, count, items.clone().map(|row| row.zip))?;
        Ok(())
    }

    fn read_group(
        r: &tdbin::Reader<'_>,
        at: usize,
        count: usize,
    ) -> Result<Vec<Self>, tdbin::DecodeError> {
        let mut street = r.var_column(at, 0, 1, count)?.into_strings()?.into_iter();
        let zip = r.i64_block_column(at, 2, count)?;
        let mut rows = Vec::with_capacity(count);
        for i in 0..count {
            rows.push(Self {
                street: street.next().ok_or(tdbin::DecodeError::MalformedColumn)?,
                zip: zip.get(i).copied().unwrap_or_default(),
            });
        }
        Ok(rows)
    }
}

impl Default for Contact {
    fn default() -> Self {
        Self::Email(EmailContact::default())
    }
}

impl tdbin::Struct for Contact {
    const DATA_WORDS: u16 = 1;
    const PTR_WORDS: u16 = 1;
    const LAYOUT_HASH: u64 = 0x8923_17b0_44d3_3a52;

    fn write_struct(&self, w: &mut tdbin::Writer, at: usize) -> Result<(), tdbin::EncodeError> {
        match self {
            Self::Email(payload) => {
                w.scalar(at, 0, 0)?;
                w.child(at, Self::DATA_WORDS, 0, Some(payload))
            }
            Self::Phone(payload) => {
                w.scalar(at, 0, 1)?;
                w.child(at, Self::DATA_WORDS, 0, Some(payload))
            }
        }
    }

    fn read_struct(r: &tdbin::Reader<'_>, at: usize) -> Result<Self, tdbin::DecodeError> {
        match r.scalar(at, 0)? {
            0 => Ok(Self::Email(
                r.child::<EmailContact>(at, Self::DATA_WORDS, 0)?
                    .unwrap_or_default(),
            )),
            1 => Ok(Self::Phone(
                r.child::<PhoneContact>(at, Self::DATA_WORDS, 0)?
                    .unwrap_or_default(),
            )),
            ordinal => {
                r.verify_struct_slots(at)?;
                Err(tdbin::DecodeError::UnknownVariant { ordinal })
            }
        }
    }
}

impl tdbin::ColumnGroup for Contact {
    const COLUMNS: u16 = 3;

    fn write_group<'v, I>(
        items: I,
        count: usize,
        w: &mut tdbin::Writer,
        at: usize,
    ) -> Result<(), tdbin::EncodeError>
    where
        I: Iterator<Item = &'v Self> + Clone,
        Self: 'v,
    {
        w.byte_column(
            at,
            1,
            0,
            count,
            items.clone().map(|row| match row {
                Self::Email(_) => 0_u8,
                Self::Phone(_) => 1_u8,
            }),
        )?;
        let email: Vec<&EmailContact> = items
            .clone()
            .filter_map(|row| match row {
                Self::Email(payload) => Some(payload),
                Self::Phone(_) => None,
            })
            .collect();
        w.dense_group(at, 1, 1, email.len(), email.iter().copied())?;
        let phone: Vec<&PhoneContact> = items
            .clone()
            .filter_map(|row| match row {
                Self::Phone(payload) => Some(payload),
                Self::Email(_) => None,
            })
            .collect();
        w.dense_group(at, 1, 2, phone.len(), phone.iter().copied())?;
        Ok(())
    }

    fn read_group(
        r: &tdbin::Reader<'_>,
        at: usize,
        count: usize,
    ) -> Result<Vec<Self>, tdbin::DecodeError> {
        let tags = r.byte_column(at, 0, count)?;
        let email_count = tags.iter().map(|tag| usize::from(*tag == 0)).sum::<usize>();
        let mut email = r
            .dense_group::<EmailContact>(at, 1, email_count)?
            .into_iter();
        let phone_count = tags.iter().map(|tag| usize::from(*tag == 1)).sum::<usize>();
        let mut phone = r
            .dense_group::<PhoneContact>(at, 2, phone_count)?
            .into_iter();
        let mut rows = Vec::with_capacity(count);
        for tag in tags {
            rows.push(match tag {
                0 => Self::Email(email.next().ok_or(tdbin::DecodeError::MalformedColumn)?),
                1 => Self::Phone(phone.next().ok_or(tdbin::DecodeError::MalformedColumn)?),
                ordinal => {
                    return Err(tdbin::DecodeError::UnknownVariant {
                        ordinal: u64::from(ordinal),
                    });
                }
            });
        }
        Ok(rows)
    }
}

impl tdbin::Struct for EmailContact {
    const DATA_WORDS: u16 = 0;
    const PTR_WORDS: u16 = 1;
    const LAYOUT_HASH: u64 = 0xace7_7873_1d2d_2d57;

    fn write_struct(&self, w: &mut tdbin::Writer, at: usize) -> Result<(), tdbin::EncodeError> {
        w.string(at, Self::DATA_WORDS, 0, Some(&self.addr))?;
        Ok(())
    }

    fn read_struct(r: &tdbin::Reader<'_>, at: usize) -> Result<Self, tdbin::DecodeError> {
        let addr = r.string(at, Self::DATA_WORDS, 0)?.unwrap_or_default();
        Ok(Self { addr })
    }
}

impl tdbin::ColumnGroup for EmailContact {
    const COLUMNS: u16 = 2;

    fn write_group<'v, I>(
        items: I,
        count: usize,
        w: &mut tdbin::Writer,
        at: usize,
    ) -> Result<(), tdbin::EncodeError>
    where
        I: Iterator<Item = &'v Self> + Clone,
        Self: 'v,
    {
        w.var_column(
            at,
            1,
            0,
            1,
            count,
            items.clone().map(|row| row.addr.as_bytes()),
        )?;
        Ok(())
    }

    fn read_group(
        r: &tdbin::Reader<'_>,
        at: usize,
        count: usize,
    ) -> Result<Vec<Self>, tdbin::DecodeError> {
        let mut addr = r.var_column(at, 0, 1, count)?.into_strings()?.into_iter();
        let mut rows = Vec::with_capacity(count);
        for _ in 0..count {
            rows.push(Self {
                addr: addr.next().ok_or(tdbin::DecodeError::MalformedColumn)?,
            });
        }
        Ok(rows)
    }
}

impl tdbin::Struct for PhoneContact {
    const DATA_WORDS: u16 = 2;
    const PTR_WORDS: u16 = 0;
    const LAYOUT_HASH: u64 = 0xf0fd_d1b3_21a6_38b5;

    fn write_struct(&self, w: &mut tdbin::Writer, at: usize) -> Result<(), tdbin::EncodeError> {
        w.scalar(at, 0, tdbin::scalar::i64_bits(self.number))?;
        w.scalar(at, 1, tdbin::scalar::i64_bits(self.country))?;
        Ok(())
    }

    fn read_struct(r: &tdbin::Reader<'_>, at: usize) -> Result<Self, tdbin::DecodeError> {
        let number = tdbin::scalar::i64_from(r.scalar(at, 0)?);
        let country = tdbin::scalar::i64_from(r.scalar(at, 1)?);
        Ok(Self { number, country })
    }
}

impl tdbin::ColumnGroup for PhoneContact {
    const COLUMNS: u16 = 2;

    fn write_group<'v, I>(
        items: I,
        count: usize,
        w: &mut tdbin::Writer,
        at: usize,
    ) -> Result<(), tdbin::EncodeError>
    where
        I: Iterator<Item = &'v Self> + Clone,
        Self: 'v,
    {
        w.i64_block_column(at, 1, 0, count, items.clone().map(|row| row.number))?;
        w.i64_block_column(at, 1, 1, count, items.clone().map(|row| row.country))?;
        Ok(())
    }

    fn read_group(
        r: &tdbin::Reader<'_>,
        at: usize,
        count: usize,
    ) -> Result<Vec<Self>, tdbin::DecodeError> {
        let number = r.i64_block_column(at, 0, count)?;
        let country = r.i64_block_column(at, 1, count)?;
        let mut rows = Vec::with_capacity(count);
        for i in 0..count {
            rows.push(Self {
                number: number.get(i).copied().unwrap_or_default(),
                country: country.get(i).copied().unwrap_or_default(),
            });
        }
        Ok(rows)
    }
}

impl tdbin::Struct for PersonBatch {
    const DATA_WORDS: u16 = 0;
    const PTR_WORDS: u16 = 1;
    const LAYOUT_HASH: u64 = 0x364e_f899_d44b_54ec;

    fn write_struct(&self, w: &mut tdbin::Writer, at: usize) -> Result<(), tdbin::EncodeError> {
        w.column_list(at, Self::DATA_WORDS, 0, Some(&self.people))?;
        Ok(())
    }

    fn read_struct(r: &tdbin::Reader<'_>, at: usize) -> Result<Self, tdbin::DecodeError> {
        let people = r
            .column_list::<Person>(at, Self::DATA_WORDS, 0)?
            .unwrap_or_default();
        Ok(Self { people })
    }
}

impl tdbin::Struct for ContactBatch {
    const DATA_WORDS: u16 = 0;
    const PTR_WORDS: u16 = 1;
    const LAYOUT_HASH: u64 = 0x81db_0e39_d4d2_e092;

    fn write_struct(&self, w: &mut tdbin::Writer, at: usize) -> Result<(), tdbin::EncodeError> {
        w.column_list(at, Self::DATA_WORDS, 0, Some(&self.contacts))?;
        Ok(())
    }

    fn read_struct(r: &tdbin::Reader<'_>, at: usize) -> Result<Self, tdbin::DecodeError> {
        let contacts = r
            .column_list::<Contact>(at, Self::DATA_WORDS, 0)?
            .unwrap_or_default();
        Ok(Self { contacts })
    }
}
